#!/usr/bin/env sh

chosen=$(grep -v "#" ~/Documents/Projects/bash_scripts/kaomoji | dmenu -i -l 10)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "${c} copied to clipboard"&

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | xclip